version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 1
    groups:
      actions-all:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "wednesday"
    open-pull-requests-limit: 1
    groups:
      gradle-all:
        patterns: ["*"]
    ignore:
      - dependency-name: "com.github.drakescraft_labs:*"
      - dependency-name: "io.papermc.paper:paper-api"
      - dependency-name: "org.spigotmc:spigot-api"
      - dependency-name: "org.bukkit:bukkit"
